### ISSUE TITLE
Xbox 360 not detected, linux

### ISSUE THREAD

**Issue by jver422** [MrCrayfish/Controllable#262]
Hi, I'm using the latest Ubuntu, forge, and minecraft Java edition. I've just downloaded the latest controllable version. 

In the settings nothing appears in the select a controller window. The controller was on when launching minecraft and it tests perfectly on game pad tester. I use these controllers to play on multiple emulators so I know they work. They are Xbox 360 wireless controllers with a wifi dongle.

Is there something I could have done wrong to get this result?

**Comment by rossperk** [comment]
I'm using MultiMC to load Forge, the Controllable mod, and launch Minecraft on Linux Mint, also with an Xbox 360 controller and wireless USB dongle. Everything seems to work, except attacking with a sword (which is a known issue, I think addressed in the next update, 1.18.2). I had to grab MultiMC deb file from their website (also JDK 17 from Oracle). I'm still learning Mint, and I'm sure there's a way to get it from repositories--I just found the website d/l first.
Just providing another Linux perspective in case anything I did helps. (Where did you get Forge?)

**Comment by VenRoot** [comment]
Same issue here, Using Pop_OS! 22.04

Minecraft is installed via Flatpak from Pop_Shop, also tried the binary file from minecraft.net 

Using an Xbox S Controller, which works in many games and is recognized by my system, but the list in the mod is empty

**Comment by VenRoot** [comment]
Fixed it!

Works after adding the binary launcher to steam, getting into Big Picture Mode, allowing the Controller for the game, then starting the game over big picture and it should show up as steam virtual gamepad

**Comment by coreybruce** [comment]
> Fixed it!
> 
> Works after adding the binary launcher to steam, getting into Big Picture Mode, allowing the Controller for the game, then starting the game over big picture and it should show up as steam virtual gamepad

That's a workaround not a actual fix.. this issue still needs to be resolved for Linux, I have the same issue on Manjaro Gnome but with a xbox one controller via bluetooth and even on Steam big picture mode it isn't working. It can see the Steam input but it doesn't work so this issue a workable work around. Don't say it's a OS issue because my controller works just fine, this mod is just sadly broken for Linux users.

**Comment by MrCrayfish** [comment]
I've written some guides on How to Connect a Gamepad. Check out the Linux section.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad

**Comment by coreybruce** [comment]
> I've written some guides on How to Connect a Gamepad. Check out the Linux section. https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad

That's great but that doesn't resolve the issue, has the issue even been fixed? can anyone else confirm?

**Comment by MrCrayfish** [comment]
@coreybruce Did you follow the Steam Virtual Gamepad guide? Make sure the controller is enabled in Steam too. At what point in the guide did the steps not work? I'm asking because there is no "fix".

**Comment by coreybruce** [comment]
> @coreybruce Did you follow the Steam Virtual Gamepad guide? Make sure the controller is enabled in Steam too. At what point in the guide did the steps not work? I'm asking because there is no "fix".

Yes I reported back in Oct 22, 2022 about it not working, I can now see virtual controller the left joystick isn't working so I can't move around.  I shouldn't need Steam virtual input to work when any other game works fine. Why does ti work on Windows properly but not on Linux? also why is there no fix?

**Comment by MrCrayfish** [comment]
"**Why does ti work on Windows properly but not on Linux?**"
Because Microsoft natively supports Xbox controllers on Windows. It's pretty easy to understand.

"**I shouldn't need Steam virtual input to work when any other game works fine**"
Any game you play from Steam with a controller will use Steam Input. 

Also it sounds to me that the mappings are out of date. The mappings available in each release Controllable are the ones that were available at the time of release. A 3 year old version of Controllable will have 3 year out of date mappings. This means gamepads release after that may not be recognized correctly. You can find a guide here to update them:
https://mrcrayfish.gitbook.io/controllable-documentation/troubleshooting/solving-incorrect-mappings

Otherwise I still suggest Steam Virtual Gamepad method if you're playing on Linux, it doesn't sound like you tried it since I only wrote the guide over a month ago, not last year.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad/method-4-steam-virtual-gamepad

**Comment by coreybruce** [comment]
"Because Microsoft natively supports Xbox controllers on Windows. It's pretty easy to understand."

Incorrect, Linux also natively supports the controller, it's a controller that uses bluetooth. while this issue is about a xbox 360 controller I am using a Xbox One controller with the same exact issue.

"Any game you play from Steam with a controller will use Steam Input."
Incorrect, games don't use steam input unless you specifically enable it in Steam also you forget that SDL/SDL2 exists that's games use including non Steam games. I Don't need Steam to play any game with a controller, that is what controller support in the system and in the game is for and I  obviously can't use Steam on my PI 4 so explain how that works and all the games on that work just fine? Clearly you know SDL exists since you are linking me to something that manages "A community sourced database of game controller mappings to be used with SDL2 Game Controller functionality"

Great to see documentation but wouldn't it be way easier for everyone if you update/maintain the gamecontrollerdb.txt file in this mod instead of relying on users to manually do this?

Look instead of just avoiding the issue, making excuses and pointing fingers how about we just cut the crap, stop the bs of blaming Linux  and just actually look into fixing the issue. No offense and not to be rude but this is a terrible way to talk to people who are trying to help report issues and how to manage a repo/project because this is a waste of my time and everyone else's time if you won't actually man up and fix the issue.

Now back to the actual problem here, why is the mod actually not detecting the controller on it's own. Can I help you figure this out and resolve this problem, I'm trying to be nice and help you but you are butting heads with me and being really rude and trying to blame me for using Linux.
