### ISSUE TITLE
Cant mine blocks when window isn't in focus.

### ISSUE THREAD

**Issue by MakoGuy** [MrCrayfish/Controllable#30]
When playing in local co-op using two separate windows, the controller will not allow mining unless the window has been clicked and brought to the front.

**Comment by MrCrayfish** [comment]
I need more information

**Comment by MakoGuy** [comment]
Sorry, playing on 1.14.4, it is an issue with every controller. No other mods.
When attempting to mine, the player arm swings as if trying to attack but does not affect blocks.

**Comment by MrCrayfish** [comment]
https://www.youtube.com/watch?v=LFpNn9iJkKQ

**Comment by MakoGuy** [comment]
Same issue after following the youtube tutorial unfortunately.

**Comment by MrCrayfish** [comment]
Are you using Windows or Mac?

**Comment by MakoGuy** [comment]
Windows 10 64bit

**Comment by MrCrayfish** [comment]
I don't know then. I've tested on Windows too so it's most likely a problem on your side. Install a clean copy of Forge installation and isolate Controllalble. Don't change any settings, don't install any extra mods. Debug the issue for me because I can't magically figured out the problem when it works perfectly on my side.

**Comment by charliebdewing** [comment]
https://github.com/MrCrayfish/Controllable/issues/30

Okay I've found how to re-create the issue:

**OS:** Windows 10 Pro - 10.0.17134
**Java Version:** jre-8u221-windows-x64
**Minecraft client:** 1.14.4 - Forge 28.1.0
**Gamepad:** PS4. Raw input with no interpreter i.e. DS4 / InputMapper
**Affected Gamemodes:** Survival / Hardcore
**Mods Installed:** Forge + Controllable 0.6.1

Open Minecraft in windowed mode.
Enable controller in settings.
Enter a Survival / Hardcore single-player game.
Open crafting or game menu.
Remove focus from Minecraft client OS by clicking outside Minecraft window.
Close menu using controller.
Attempt to destroy a block.

When I do the above steps I am unable to break any blocks. It plays the interaction animation but does not affect the block.
I **can** however place blocks, interact with tables, destroy grass / plants and hit mobs with no apparent issues.

Hopefully you're seeing the same thing.

My guess is something to do with the Minecraft client checking to see if the window is focused before it grants permission to destroy blocks in Survival Modes.

Seems to relate to this issue: https://www.minecraftforum.net/forums/archive/legacy-support/1757414-cant-click-on-anything-after-minecraft-loses

Happy to help any way I can. Thanks for a fantastic mod!

**Comment by MrCrayfish** [comment]
Thank you for actually providing some details on this issue. I will reopen this and investigate futher.

**Comment by alexispierret** [comment]
Hi there, 
Any lead on where to look at for this one ?
Java dev but never played with Minecraft mods, could look a bit around.
Would really need this bug fixes otherwise it's not possible to co-op on 1.14 locally :-)
Great mod nevertheless !
Cheers,
Alexis

**Comment by skeddles** [comment]
I'm getting this problem too. I recently started using controllable (used to use joystick mod). We use it to play multiplayer on one computer, but the out of focus player can't break blocks, they seem to press the button quickly but it wont stay held down long enough to mine (you can break grass though). It does work fine when the window is in focus. Just isn't playable when you want to use it for multiplayer.

Windows 10
MC 14.4.4
controllable-1.14.4-0.6.1
Gamepad: Wired XBOX 360, but it says "ShanWan PS3/PC Wired GamePad" in controllable.

If there's anything else I can do to help fix it let me know, we would love to get co-op working in 1.14!

**Comment by Vladgina** [comment]
Please fix this. I too tried using PS4 controller with ONLY this mod and it works great! Until I want to break something. I need to keep focus on the 2nd Minecraft window since I use keyboard + Mouse for that while my family member uses controller on 1st Minecraft window. We are so close to finally playing COOP Minecraft on a single computer but this one thing is ruining the experience. 1 person being unable to break blocks is a huge handicap and not very fun for either of us.

**Comment by MrCrayfish** [comment]
Which version of the mod are you running?

**Comment by Vladgina** [comment]
I'm using 1.15.2 for Fabric. If it's fixed on Forge I guess I'll switch but I really have had nothing but problems with Forge.

**Comment by MrCrayfish** [comment]
I don't control the Fabric version. It's a fan maintained version.

**Comment by MrCrayfish** [comment]
Is anyone able to confirm this is still an issue on recent versions? Please make sure "pause on unfocus" is turned off (F3 + P)

**Comment by wysus** [comment]
> Is anyone able to confirm this is still an issue on recent versions? Please make sure "pause on unfocus" is turned off (F3 + P)

yep, im playing on 1.16.3 with controllable mod ver 0.10.0 and everything works fine but i cant destroy any blocks on ps4 controller

**Comment by MrCrayfish** [comment]
Update to version 0.10.1, 0.10.0 is broken.

**Comment by MrCrayfish** [comment]
I still can't seem to reproduce (no mods, just Controllable). If anyone has had the problem, can you test with only Controllable installed (No optifine)? Make sure you are using the latest version!

**Comment by MrCrayfish** [comment]
Also won't be updating anything less than 1.15.2

**Comment by jeffredrose** [comment]
Same problem on 1.16.5

**Comment by jeffredrose** [comment]
Hold down right trigger not working on Xbox one controller everything else is fine

**Comment by MrCrayfish** [comment]
Is this an issue on modern versions of controllable? e.g on 1.18.2 or above?

**Comment by TomHodson** [comment]
I’m on osx, controllable 0.19.0 and Minecraft 1.19.4. When trying to play coop I can break blocks but I can’t eat food or use the spyglass (when the window doesn’t have focus). Could this be the same issue?

**Comment by MrCrayfish** [comment]
@TomHodson Download the new update 0.19.1

**Comment by MrCrayfish** [comment]
@TomHodson Was this an issue on versions prior to 0.19.0?

**Comment by TomHodson** [comment]
I never played with anything below 0.19.0. I can confirm that I just installed 0.19.1 and the issue is now fixed. I can install an earlier version to check if the bug is there if it would be helpful. Appreciate the mod by the way!

**Comment by MrCrayfish** [comment]
I had in my mind that you were using the Fabric version (just released recently), however if you've updated to 0.19.1 on Forge, that should solve the problem.

**Comment by TomHodson** [comment]
Yeah sorry, forgot to mention I was on Forge, and yes 0.19.1 fixes my issue with the right click action only working for actions that require short clicks and not for long clicks like eating food or using the spyglass. Can I ask was it the same underlying issue that affected  both the left and right click actions?

**Comment by MrCrayfish** [comment]
@TomHodson It's not the same issue, I accidentally forgot to apply some code when I was porting the multiloader branch back to the forge branch. As for the original issue, I was never able to reproduce the issue or find the potential cause. There also hasn't been any subsequent issues, so potentially it has been fixed with all the updates since 2019 (refactored the code a lot and change input libraries multiple times).

**Comment by aLiteral-potato** [comment]
Still experiencing this problem with 19.4+1.20 on 1.20.1 with fabric.
im running a modpack called "landscapes reimagined genesis" with iris and distant horizons added on, if that helps with possible problems regarding possible mod incompatibilities.
